[project]
name = "project-school"
version = "0.1.0"
description = ""
authors = [
    {name = "Daniel-Merquiades",email = "danielmbraz04@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib (>=3.10.9,<4.0.0)",
    "pandas (>=3.0.2,<4.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "streamlit (>=1.57.0,<2.0.0)",
    "speechrecognition (>=3.16.1,<4.0.0)",
    "pyttsx3 (>=2.99,<3.0)",
    "numpy (>=2.4.4,<3.0.0)"
]

[tool.poetry]
packages = [{include = "project_school", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.2.0,<8.0.0)"
]
