from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
import pickle
import os

# NÃO RODE ESSE CÓDIGO! CASO FAÇA ISSO A IA IRÁ RESETAR, JOGANDO TODO APRENDIZADO DELA NO LIXO. Caso não tenha ensinado nada a ela, pode rodar de boa.

Dados = [
    #Comandos para ligar luzes

    ("liga a luz", "ligar_luz"),
    ("ligar a luz", "ligar_luz"),
    ("ligue a luz", "ligar_luz"),
    ("liga as luzes", "ligar_luz"),
    ("ligar as luzes", "ligar_luz"),
    ("ligue as luzes", "ligar_luz"),
    ("ligar luz", "ligar_luz"),
    ("ligar luzes", "ligar_luz"),
    ("acender luz", "ligar_luz"),
    ("acender luzes", "ligar_luz"),
    ("acenda a luz", "ligar_luz"),
    ("acenda as luzes", "ligar_luz"),
    ("acende a luz", "ligar_luz"),
    ("acende as luzes", "ligar_luz"),
    ("ascender luzes", "ligar_luz"),
    ("ascenda as luzes", "ligar_luz"),
    ("iluminar a escola", "ligar_luz"),
    ("ilumine a escola", "ligar_luz"),
    ("iluminar todas as salas", "ligar_luz"),
    ("ligar iluminação", "ligar_luz"),
    ("ligar a iluminação", "ligar_luz"),
    ("ligue a iluminação", "ligar_luz"),
    ("acender iluminação", "ligar_luz"),
    ("ativar iluminação", "ligar_luz"),
    ("ative a iluminação", "ligar_luz"),
    ("iniciar iluminação", "ligar_luz"),
    ("iniciar luzes", "ligar_luz"),
    ("ativar luzes", "ligar_luz"),
    ("ative as luzes", "ligar_luz"),
    ("quero luz", "ligar_luz"),
    ("quero as luzes acesas", "ligar_luz"),
    ("quero todas as luzes acesas", "ligar_luz"),
    ("deixe tudo iluminado", "ligar_luz"),
    ("deixe a escola iluminada", "ligar_luz"),
    ("ligue toda a iluminação", "ligar_luz"),
    ("acenda toda a iluminação", "ligar_luz"),
    ("ligue todas as luzes", "ligar_luz"),
    ("acenda todas as luzes", "ligar_luz"),
    ("ligar todas as luzes da escola", "ligar_luz"),
    ("acender todas as luzes da escola", "ligar_luz"),
    ("ligue todas as luzes da escola", "ligar_luz"),
    ("acenda todas as luzes da escola", "ligar_luz"),
    ("ligar iluminação da escola", "ligar_luz"),
    ("acender iluminação da escola", "ligar_luz"),
    ("ligue a iluminação da escola", "ligar_luz"),
    ("acenda a iluminação da escola", "ligar_luz"),
    ("ligar luzes da escola", "ligar_luz"),
    ("acender luzes da escola", "ligar_luz"),
    ("ilumine todas as salas", "ligar_luz"),
    ("ilumine todos os ambientes", "ligar_luz"),
    ("ligue a energia das luzes", "ligar_luz"),
    ("ativar sistema de iluminação", "ligar_luz"),
    ("ative o sistema de iluminação", "ligar_luz"),
    ("ligar iluminação geral", "ligar_luz"),
    ("acender iluminação geral", "ligar_luz"),
    ("ligue a iluminação geral", "ligar_luz"),
    ("acenda a iluminação geral", "ligar_luz"),
    ("ligar todas as lâmpadas", "ligar_luz"),
    ("acender todas as lâmpadas", "ligar_luz"),
    ("ligue todas as lâmpadas", "ligar_luz"),
    ("acenda todas as lâmpadas", "ligar_luz"),
    ("liga tudo", "ligar_luz"),
    ("liga tudo que é luz", "ligar_luz"),
    ("acende tudo", "ligar_luz"),
    ("acende tudo na escola", "ligar_luz"),
    ("liga a iluminação completa", "ligar_luz"),
    ("acende a iluminação completa", "ligar_luz"),
    ("ligar luzes internas", "ligar_luz"),
    ("acender luzes internas", "ligar_luz"),
    ("ligar todas as luzes internas", "ligar_luz"),
    ("acender todas as luzes internas", "ligar_luz"),
    ("ligue todas as salas", "ligar_luz"),
    ("acenda todas as salas", "ligar_luz"),
    ("ilumine o prédio", "ligar_luz"),
    ("ilumine toda a escola", "ligar_luz"),
    ("coloque todas as luzes para funcionar", "ligar_luz"),
    ("deixe todas as luzes ligadas", "ligar_luz"),
    ("preciso de iluminação", "ligar_luz"),
    ("quero iluminar o ambiente", "ligar_luz"),
    ("liga as luzes de todo o prédio", "ligar_luz"),
    ("acende as luzes de todo o prédio", "ligar_luz"),
    ("ative todas as luzes", "ligar_luz"),
    ("ligue o sistema de luzes", "ligar_luz"),
    ("acione a iluminação", "ligar_luz"),
    ("coloque a escola em modo iluminado", "ligar_luz"),
    ("clareie a escola", "ligar_luz"),
    ("clareie todos os ambientes", "ligar_luz"),
    ("mais luz na escola", "ligar_luz"),
    ("quero a escola toda iluminada", "ligar_luz"),
    ("deixe todas as salas acesas", "ligar_luz"),
    ("ligue as luzes de todas as salas", "ligar_luz"),
    ("acenda as luzes de todas as salas", "ligar_luz"),


    # Ligar sala 1

    ("liga a sala 1", "ligar_sala1"),
    ("liga a sala um", "ligar_sala1"),
    ("ligar a sala 1", "ligar_sala1"),
    ("ligar a sala um", "ligar_sala1"),
    ("ligue a sala 1", "ligar_sala1"),
    ("ligue a sala um", "ligar_sala1"),
    ("acende a sala 1", "ligar_sala1"),
    ("acende a sala um", "ligar_sala1"),
    ("acender a sala 1", "ligar_sala1"),
    ("acender a sala um", "ligar_sala1"),
    ("acenda a sala 1", "ligar_sala1"),
    ("acenda a sala um", "ligar_sala1"),
    ("ilumina a sala 1", "ligar_sala1"),
    ("ilumina a sala um", "ligar_sala1"),
    ("ilumine a sala 1", "ligar_sala1"),
    ("ilumine a sala um", "ligar_sala1"),
    ("ligar sala 1", "ligar_sala1"),
    ("ligar sala um", "ligar_sala1"),
    ("acender sala 1", "ligar_sala1"),
    ("acender sala um", "ligar_sala1"),
    ("ligar a luz da sala 1", "ligar_sala1"),
    ("ligar a luz da sala um", "ligar_sala1"),
    ("ligue a luz da sala 1", "ligar_sala1"),
    ("ligue a luz da sala um", "ligar_sala1"),
    ("acenda a luz da sala 1", "ligar_sala1"),
    ("acenda a luz da sala um", "ligar_sala1"),
    ("acende a luz da sala 1", "ligar_sala1"),
    ("acende a luz da sala um", "ligar_sala1"),
    ("luz da sala 1", "ligar_sala1"),
    ("luz da sala um", "ligar_sala1"),
    ("ligar as luzes da sala 1", "ligar_sala1"),
    ("ligar as luzes da sala um", "ligar_sala1"),
    ("ligue as luzes da sala 1", "ligar_sala1"),
    ("ligue as luzes da sala um", "ligar_sala1"),
    ("acender as luzes da sala 1", "ligar_sala1"),
    ("acender as luzes da sala um", "ligar_sala1"),
    ("acenda as luzes da sala 1", "ligar_sala1"),
    ("acenda as luzes da sala um", "ligar_sala1"),
    ("ative a iluminação da sala 1", "ligar_sala1"),
    ("ative a iluminação da sala um", "ligar_sala1"),
    ("ativar iluminação da sala 1", "ligar_sala1"),
    ("ativar iluminação da sala um", "ligar_sala1"),
    ("ligue a iluminação da sala 1", "ligar_sala1"),
    ("ligue a iluminação da sala um", "ligar_sala1"),
    ("acenda a iluminação da sala 1", "ligar_sala1"),
    ("acenda a iluminação da sala um", "ligar_sala1"),
    ("quero luz na sala 1", "ligar_sala1"),
    ("quero luz na sala um", "ligar_sala1"),
    ("quero a sala 1 iluminada", "ligar_sala1"),
    ("quero a sala um iluminada", "ligar_sala1"),
    ("deixe a sala 1 iluminada", "ligar_sala1"),
    ("deixe a sala um iluminada", "ligar_sala1"),
    ("coloque luz na sala 1", "ligar_sala1"),
    ("coloque luz na sala um", "ligar_sala1"),
    ("mais luz na sala 1", "ligar_sala1"),
    ("mais luz na sala um", "ligar_sala1"),
    ("clareie a sala 1", "ligar_sala1"),
    ("clareie a sala um", "ligar_sala1"),
    ("ilumine o ambiente da sala 1", "ligar_sala1"),
    ("ilumine o ambiente da sala um", "ligar_sala1"),
    ("pode ligar a sala 1", "ligar_sala1"),
    ("pode ligar a sala um", "ligar_sala1"),
    ("por favor ligue a sala 1", "ligar_sala1"),
    ("por favor ligue a sala um", "ligar_sala1"),
    ("gostaria de ligar a sala 1", "ligar_sala1"),
    ("gostaria de ligar a sala um", "ligar_sala1"),
    ("preciso de luz na sala 1", "ligar_sala1"),
    ("preciso de luz na sala um", "ligar_sala1"),
    ("ligue somente a sala 1", "ligar_sala1"),
    ("ligue somente a sala um", "ligar_sala1"),
    ("acenda somente a sala 1", "ligar_sala1"),
    ("acenda somente a sala um", "ligar_sala1"),
    ("ligue apenas a sala 1", "ligar_sala1"),
    ("ligue apenas a sala um", "ligar_sala1"),
    ("acenda apenas a sala 1", "ligar_sala1"),
    ("acenda apenas a sala um", "ligar_sala1"),
    ("quero estudar na sala 1", "ligar_sala1"),
    ("quero estudar na sala um", "ligar_sala1"),
    ("prepare a sala 1", "ligar_sala1"),
    ("prepare a sala um", "ligar_sala1"),
    ("deixe a sala 1 pronta", "ligar_sala1"),
    ("deixe a sala um pronta", "ligar_sala1"),
    ("liga a iluminação da sala 1", "ligar_sala1"),
    ("liga a iluminação da sala um", "ligar_sala1"),
    ("acende a iluminação da sala 1", "ligar_sala1"),
    ("acende a iluminação da sala um", "ligar_sala1"),
    ("coloque a sala 1 em funcionamento", "ligar_sala1"),
    ("coloque a sala um em funcionamento", "ligar_sala1"),


    # Apagar sala 1

    ("apaga a sala 1", "apagar_sala1"),
    ("apaga a sala um", "apagar_sala1"),
    ("apagar a sala 1", "apagar_sala1"),
    ("apagar a sala um", "apagar_sala1"),
    ("apague a sala 1", "apagar_sala1"),
    ("apague a sala um", "apagar_sala1"),
    ("desliga a sala 1", "apagar_sala1"),
    ("desliga a sala um", "apagar_sala1"),
    ("desligar a sala 1", "apagar_sala1"),
    ("desligar a sala um", "apagar_sala1"),
    ("desligue a sala 1", "apagar_sala1"),
    ("desligue a sala um", "apagar_sala1"),
    ("apagar sala 1", "apagar_sala1"),
    ("apagar sala um", "apagar_sala1"),
    ("desligar sala 1", "apagar_sala1"),
    ("desligar sala um", "apagar_sala1"),
    ("apague a luz da sala 1", "apagar_sala1"),
    ("apague a luz da sala um", "apagar_sala1"),
    ("desligue a luz da sala 1", "apagar_sala1"),
    ("desligue a luz da sala um", "apagar_sala1"),
    ("apaga a luz da sala 1", "apagar_sala1"),
    ("apaga a luz da sala um", "apagar_sala1"),
    ("desliga a luz da sala 1", "apagar_sala1"),
    ("desliga a luz da sala um", "apagar_sala1"),
    ("apagar as luzes da sala 1", "apagar_sala1"),
    ("apagar as luzes da sala um", "apagar_sala1"),
    ("desligar as luzes da sala 1", "apagar_sala1"),
    ("desligar as luzes da sala um", "apagar_sala1"),
    ("apague as luzes da sala 1", "apagar_sala1"),
    ("apague as luzes da sala um", "apagar_sala1"),
    ("desligue as luzes da sala 1", "apagar_sala1"),
    ("desligue as luzes da sala um", "apagar_sala1"),
    ("apaga a iluminação da sala 1", "apagar_sala1"),
    ("apaga a iluminação da sala um", "apagar_sala1"),
    ("desliga a iluminação da sala 1", "apagar_sala1"),
    ("desliga a iluminação da sala um", "apagar_sala1"),
    ("apagar a iluminação da sala 1", "apagar_sala1"),
    ("apagar a iluminação da sala um", "apagar_sala1"),
    ("desligar a iluminação da sala 1", "apagar_sala1"),
    ("desligar a iluminação da sala um", "apagar_sala1"),
    ("desative a iluminação da sala 1", "apagar_sala1"),
    ("desative a iluminação da sala um", "apagar_sala1"),
    ("quero apagar a sala 1", "apagar_sala1"),
    ("quero apagar a sala um", "apagar_sala1"),
    ("quero a sala 1 escura", "apagar_sala1"),
    ("quero a sala um escura", "apagar_sala1"),
    ("deixe a sala 1 escura", "apagar_sala1"),
    ("deixe a sala um escura", "apagar_sala1"),
    ("sem luz na sala 1", "apagar_sala1"),
    ("sem luz na sala um", "apagar_sala1"),
    ("retire a iluminação da sala 1", "apagar_sala1"),
    ("retire a iluminação da sala um", "apagar_sala1"),
    ("escureça a sala 1", "apagar_sala1"),
    ("escureça a sala um", "apagar_sala1"),
    ("apague somente a sala 1", "apagar_sala1"),
    ("apague somente a sala um", "apagar_sala1"),
    ("desligue somente a sala 1", "apagar_sala1"),
    ("desligue somente a sala um", "apagar_sala1"),
    ("apague apenas a sala 1", "apagar_sala1"),
    ("apague apenas a sala um", "apagar_sala1"),
    ("desligue apenas a sala 1", "apagar_sala1"),
    ("desligue apenas a sala um", "apagar_sala1"),
    ("pode apagar a sala 1", "apagar_sala1"),
    ("pode apagar a sala um", "apagar_sala1"),
    ("por favor apague a sala 1", "apagar_sala1"),
    ("por favor apague a sala um", "apagar_sala1"),
    ("gostaria de apagar a sala 1", "apagar_sala1"),
    ("gostaria de apagar a sala um", "apagar_sala1"),
    ("não preciso mais de luz na sala 1", "apagar_sala1"),
    ("não preciso mais de luz na sala um", "apagar_sala1"),
    ("desative as luzes da sala 1", "apagar_sala1"),
    ("desative as luzes da sala um", "apagar_sala1"),
    ("desligue o ambiente da sala 1", "apagar_sala1"),
    ("desligue o ambiente da sala um", "apagar_sala1"),
    ("apague tudo na sala 1", "apagar_sala1"),
    ("apague tudo na sala um", "apagar_sala1"),
    ("desligue tudo na sala 1", "apagar_sala1"),
    ("desligue tudo na sala um", "apagar_sala1"),
    ("desliga a iluminação da sala 1", "apagar_sala1"),
    ("desliga a iluminação da sala um", "apagar_sala1"),
    ("luz da sala 1 apagada", "apagar_sala1"),
    ("luz da sala um apagada", "apagar_sala1"),
    ("quero a luz da sala 1 apagada", "apagar_sala1"),
    ("quero a luz da sala um apagada", "apagar_sala1"),


    # Ligar sala 2

    ("liga a sala 2", "ligar_sala2"),
    ("liga a sala dois", "ligar_sala2"),
    ("ligar a sala 2", "ligar_sala2"),
    ("ligar a sala dois", "ligar_sala2"),
    ("ligue a sala 2", "ligar_sala2"),
    ("ligue a sala dois", "ligar_sala2"),
    ("acende a sala 2", "ligar_sala2"),
    ("acende a sala dois", "ligar_sala2"),
    ("acender a sala 2", "ligar_sala2"),
    ("acender a sala dois", "ligar_sala2"),
    ("acenda a sala 2", "ligar_sala2"),
    ("acenda a sala dois", "ligar_sala2"),
    ("ilumina a sala 2", "ligar_sala2"),
    ("ilumina a sala dois", "ligar_sala2"),
    ("ilumine a sala 2", "ligar_sala2"),
    ("ilumine a sala dois", "ligar_sala2"),
    ("ligar sala 2", "ligar_sala2"),
    ("ligar sala dois", "ligar_sala2"),
    ("acender sala 2", "ligar_sala2"),
    ("acender sala dois", "ligar_sala2"),
    ("ligar a luz da sala 2", "ligar_sala2"),
    ("ligar a luz da sala dois", "ligar_sala2"),
    ("ligue a luz da sala 2", "ligar_sala2"),
    ("ligue a luz da sala dois", "ligar_sala2"),
    ("acenda a luz da sala 2", "ligar_sala2"),
    ("acenda a luz da sala dois", "ligar_sala2"),
    ("acende a luz da sala 2", "ligar_sala2"),
    ("acende a luz da sala dois", "ligar_sala2"),
    ("luz da sala 2", "ligar_sala2"),
    ("luz da sala dois", "ligar_sala2"),
    ("ligar as luzes da sala 2", "ligar_sala2"),
    ("ligar as luzes da sala dois", "ligar_sala2"),
    ("ligue as luzes da sala 2", "ligar_sala2"),
    ("ligue as luzes da sala dois", "ligar_sala2"),
    ("acender as luzes da sala 2", "ligar_sala2"),
    ("acender as luzes da sala dois", "ligar_sala2"),
    ("acenda as luzes da sala 2", "ligar_sala2"),
    ("acenda as luzes da sala dois", "ligar_sala2"),
    ("ative a iluminação da sala 2", "ligar_sala2"),
    ("ative a iluminação da sala dois", "ligar_sala2"),
    ("ativar iluminação da sala 2", "ligar_sala2"),
    ("ativar iluminação da sala dois", "ligar_sala2"),
    ("ligue a iluminação da sala 2", "ligar_sala2"),
    ("ligue a iluminação da sala dois", "ligar_sala2"),
    ("acenda a iluminação da sala 2", "ligar_sala2"),
    ("acenda a iluminação da sala dois", "ligar_sala2"),
    ("quero luz na sala 2", "ligar_sala2"),
    ("quero luz na sala dois", "ligar_sala2"),
    ("quero a sala 2 iluminada", "ligar_sala2"),
    ("quero a sala dois iluminada", "ligar_sala2"),
    ("deixe a sala 2 iluminada", "ligar_sala2"),
    ("deixe a sala dois iluminada", "ligar_sala2"),
    ("coloque luz na sala 2", "ligar_sala2"),
    ("coloque luz na sala dois", "ligar_sala2"),
    ("mais luz na sala 2", "ligar_sala2"),
    ("mais luz na sala dois", "ligar_sala2"),
    ("clareie a sala 2", "ligar_sala2"),
    ("clareie a sala dois", "ligar_sala2"),
    ("ilumine o ambiente da sala 2", "ligar_sala2"),
    ("ilumine o ambiente da sala dois", "ligar_sala2"),
    ("pode ligar a sala 2", "ligar_sala2"),
    ("pode ligar a sala dois", "ligar_sala2"),
    ("por favor ligue a sala 2", "ligar_sala2"),
    ("por favor ligue a sala dois", "ligar_sala2"),
    ("gostaria de ligar a sala 2", "ligar_sala2"),
    ("gostaria de ligar a sala dois", "ligar_sala2"),
    ("preciso de luz na sala 2", "ligar_sala2"),
    ("preciso de luz na sala dois", "ligar_sala2"),
    ("ligue somente a sala 2", "ligar_sala2"),
    ("ligue somente a sala dois", "ligar_sala2"),
    ("acenda somente a sala 2", "ligar_sala2"),
    ("acenda somente a sala dois", "ligar_sala2"),
    ("ligue apenas a sala 2", "ligar_sala2"),
    ("ligue apenas a sala dois", "ligar_sala2"),
    ("acenda apenas a sala 2", "ligar_sala2"),
    ("acenda apenas a sala dois", "ligar_sala2"),
    ("quero estudar na sala 2", "ligar_sala2"),
    ("quero estudar na sala dois", "ligar_sala2"),
    ("prepare a sala 2", "ligar_sala2"),
    ("prepare a sala dois", "ligar_sala2"),
    ("deixe a sala 2 pronta", "ligar_sala2"),
    ("deixe a sala dois pronta", "ligar_sala2"),
    ("liga a iluminação da sala 2", "ligar_sala2"),
    ("liga a iluminação da sala dois", "ligar_sala2"),
    ("acende a iluminação da sala 2", "ligar_sala2"),
    ("acende a iluminação da sala dois", "ligar_sala2"),
    ("coloque a sala 2 em funcionamento", "ligar_sala2"),
    ("coloque a sala dois em funcionamento", "ligar_sala2"),



    # Apagar sala 2

    ("apaga a sala 2", "apagar_sala2"),
    ("apaga a sala dois", "apagar_sala2"),
    ("apagar a sala 2", "apagar_sala2"),
    ("apagar a sala dois", "apagar_sala2"),
    ("apague a sala 2", "apagar_sala2"),
    ("apague a sala dois", "apagar_sala2"),
    ("desliga a sala 2", "apagar_sala2"),
    ("desliga a sala dois", "apagar_sala2"),
    ("desligar a sala 2", "apagar_sala2"),
    ("desligar a sala dois", "apagar_sala2"),
    ("desligue a sala 2", "apagar_sala2"),
    ("desligue a sala dois", "apagar_sala2"),
    ("apagar sala 2", "apagar_sala2"),
    ("apagar sala dois", "apagar_sala2"),
    ("desligar sala 2", "apagar_sala2"),
    ("desligar sala dois", "apagar_sala2"),
    ("apague a luz da sala 2", "apagar_sala2"),
    ("apague a luz da sala dois", "apagar_sala2"),
    ("desligue a luz da sala 2", "apagar_sala2"),
    ("desligue a luz da sala dois", "apagar_sala2"),
    ("apaga a luz da sala 2", "apagar_sala2"),
    ("apaga a luz da sala dois", "apagar_sala2"),
    ("desliga a luz da sala 2", "apagar_sala2"),
    ("desliga a luz da sala dois", "apagar_sala2"),
    ("apagar as luzes da sala 2", "apagar_sala2"),
    ("apagar as luzes da sala dois", "apagar_sala2"),
    ("desligar as luzes da sala 2", "apagar_sala2"),
    ("desligar as luzes da sala dois", "apagar_sala2"),
    ("apague as luzes da sala 2", "apagar_sala2"),
    ("apague as luzes da sala dois", "apagar_sala2"),
    ("desligue as luzes da sala 2", "apagar_sala2"),
    ("desligue as luzes da sala dois", "apagar_sala2"),
    ("apaga a iluminação da sala 2", "apagar_sala2"),
    ("apaga a iluminação da sala dois", "apagar_sala2"),
    ("desliga a iluminação da sala 2", "apagar_sala2"),
    ("desliga a iluminação da sala dois", "apagar_sala2"),
    ("apagar a iluminação da sala 2", "apagar_sala2"),
    ("apagar a iluminação da sala dois", "apagar_sala2"),
    ("desligar a iluminação da sala 2", "apagar_sala2"),
    ("desligar a iluminação da sala dois", "apagar_sala2"),
    ("desative a iluminação da sala 2", "apagar_sala2"),
    ("desative a iluminação da sala dois", "apagar_sala2"),
    ("quero apagar a sala 2", "apagar_sala2"),
    ("quero apagar a sala dois", "apagar_sala2"),
    ("quero a sala 2 escura", "apagar_sala2"),
    ("quero a sala dois escura", "apagar_sala2"),
    ("deixe a sala 2 escura", "apagar_sala2"),
    ("deixe a sala dois escura", "apagar_sala2"),
    ("sem luz na sala 2", "apagar_sala2"),
    ("sem luz na sala dois", "apagar_sala2"),
    ("retire a iluminação da sala 2", "apagar_sala2"),
    ("retire a iluminação da sala dois", "apagar_sala2"),
    ("escureça a sala 2", "apagar_sala2"),
    ("escureça a sala dois", "apagar_sala2"),
    ("apague somente a sala 2", "apagar_sala2"),
    ("apague somente a sala dois", "apagar_sala2"),
    ("desligue somente a sala 2", "apagar_sala2"),
    ("desligue somente a sala dois", "apagar_sala2"),
    ("apague apenas a sala 2", "apagar_sala2"),
    ("apague apenas a sala dois", "apagar_sala2"),
    ("desligue apenas a sala 2", "apagar_sala2"),
    ("desligue apenas a sala dois", "apagar_sala2"),
    ("pode apagar a sala 2", "apagar_sala2"),
    ("pode apagar a sala dois", "apagar_sala2"),
    ("por favor apague a sala 2", "apagar_sala2"),
    ("por favor apague a sala dois", "apagar_sala2"),
    ("gostaria de apagar a sala 2", "apagar_sala2"),
    ("gostaria de apagar a sala dois", "apagar_sala2"),
    ("não preciso mais de luz na sala 2", "apagar_sala2"),
    ("não preciso mais de luz na sala dois", "apagar_sala2"),
    ("desative as luzes da sala 2", "apagar_sala2"),
    ("desative as luzes da sala dois", "apagar_sala2"),
    ("desligue o ambiente da sala 2", "apagar_sala2"),
    ("desligue o ambiente da sala dois", "apagar_sala2"),
    ("apague tudo na sala 2", "apagar_sala2"),
    ("apague tudo na sala dois", "apagar_sala2"),
    ("desligue tudo na sala 2", "apagar_sala2"),
    ("desligue tudo na sala dois", "apagar_sala2"),
    ("desliga a iluminação da sala 2", "apagar_sala2"),
    ("desliga a iluminação da sala dois", "apagar_sala2"),
    ("luz da sala 2 apagada", "apagar_sala2"),
    ("luz da sala dois apagada", "apagar_sala2"),
    ("quero a luz da sala 2 apagada", "apagar_sala2"),
    ("quero a luz da sala dois apagada", "apagar_sala2"),



    # Ligar coordenação

    ("liga a coordenação", "ligar_coordenacao"),
    ("ligar coordenação", "ligar_coordenacao"),
    ("ligar a coordenação", "ligar_coordenacao"),
    ("ligue a coordenação", "ligar_coordenacao"),
    ("acende a coordenação", "ligar_coordenacao"),
    ("acender coordenação", "ligar_coordenacao"),
    ("acender a coordenação", "ligar_coordenacao"),
    ("acenda a coordenação", "ligar_coordenacao"),
    ("luz da coordenação", "ligar_coordenacao"),
    ("ligar a luz da coordenação", "ligar_coordenacao"),
    ("ligue a luz da coordenação", "ligar_coordenacao"),
    ("acenda a luz da coordenação", "ligar_coordenacao"),
    ("ilumina a coordenação", "ligar_coordenacao"),
    ("ilumine a coordenação", "ligar_coordenacao"),
    ("ligar as luzes da coordenação", "ligar_coordenacao"),
    ("ligue as luzes da coordenação", "ligar_coordenacao"),
    ("acender as luzes da coordenação", "ligar_coordenacao"),
    ("acenda as luzes da coordenação", "ligar_coordenacao"),
    ("ligar a iluminação da coordenação", "ligar_coordenacao"),
    ("acender a iluminação da coordenação", "ligar_coordenacao"),
    ("ative a iluminação da coordenação", "ligar_coordenacao"),
    ("quero luz na coordenação", "ligar_coordenacao"),
    ("quero a coordenação iluminada", "ligar_coordenacao"),
    ("deixe a coordenação iluminada", "ligar_coordenacao"),
    ("coordenação luz", "ligar_coordenacao"),
    ("mais luz na coordenação", "ligar_coordenacao"),
    ("clareie a coordenação", "ligar_coordenacao"),
    ("pode ligar a coordenação", "ligar_coordenacao"),
    ("por favor ligue a coordenação", "ligar_coordenacao"),
    ("preciso de luz na coordenação", "ligar_coordenacao"),
    ("liga a secretaria", "ligar_coordenacao"),
    ("ligar secretaria", "ligar_coordenacao"),
    ("ligar a secretaria", "ligar_coordenacao"),
    ("ligue a secretaria", "ligar_coordenacao"),
    ("acende a secretaria", "ligar_coordenacao"),
    ("acender secretaria", "ligar_coordenacao"),
    ("acender a secretaria", "ligar_coordenacao"),
    ("acenda a secretaria", "ligar_coordenacao"),
    ("luz da secretaria", "ligar_coordenacao"),
    ("ligar a luz da secretaria", "ligar_coordenacao"),
    ("ligue a luz da secretaria", "ligar_coordenacao"),
    ("acenda a luz da secretaria", "ligar_coordenacao"),
    ("ilumina a secretaria", "ligar_coordenacao"),
    ("ilumine a secretaria", "ligar_coordenacao"),
    ("ligar as luzes da secretaria", "ligar_coordenacao"),
    ("ligue as luzes da secretaria", "ligar_coordenacao"),
    ("acender as luzes da secretaria", "ligar_coordenacao"),
    ("acenda as luzes da secretaria", "ligar_coordenacao"),
    ("ligar a iluminação da secretaria", "ligar_coordenacao"),
    ("acender a iluminação da secretaria", "ligar_coordenacao"),
    ("ative a iluminação da secretaria", "ligar_coordenacao"),
    ("quero luz na secretaria", "ligar_coordenacao"),
    ("quero a secretaria iluminada", "ligar_coordenacao"),
    ("deixe a secretaria iluminada", "ligar_coordenacao"),
    ("secretaria luz", "ligar_coordenacao"),
    ("mais luz na secretaria", "ligar_coordenacao"),
    ("clareie a secretaria", "ligar_coordenacao"),
    ("pode ligar a secretaria", "ligar_coordenacao"),
    ("por favor ligue a secretaria", "ligar_coordenacao"),
    ("preciso de luz na secretaria", "ligar_coordenacao"),
    ("liga a diretoria", "ligar_coordenacao"),
    ("ligar diretoria", "ligar_coordenacao"),
    ("ligar a diretoria", "ligar_coordenacao"),
    ("ligue a diretoria", "ligar_coordenacao"),
    ("acende a diretoria", "ligar_coordenacao"),
    ("acender diretoria", "ligar_coordenacao"),
    ("acender a diretoria", "ligar_coordenacao"),
    ("acenda a diretoria", "ligar_coordenacao"),
    ("luz da diretoria", "ligar_coordenacao"),
    ("ligar a luz da diretoria", "ligar_coordenacao"),
    ("ligue a luz da diretoria", "ligar_coordenacao"),
    ("acenda a luz da diretoria", "ligar_coordenacao"),
    ("ilumina a diretoria", "ligar_coordenacao"),
    ("ilumine a diretoria", "ligar_coordenacao"),
    ("ligar as luzes da diretoria", "ligar_coordenacao"),
    ("ligue as luzes da diretoria", "ligar_coordenacao"),
    ("acender as luzes da diretoria", "ligar_coordenacao"),
    ("acenda as luzes da diretoria", "ligar_coordenacao"),
    ("ligar a iluminação da diretoria", "ligar_coordenacao"),
    ("acender a iluminação da diretoria", "ligar_coordenacao"),
    ("ative a iluminação da diretoria", "ligar_coordenacao"),
    ("quero luz na diretoria", "ligar_coordenacao"),
    ("quero a diretoria iluminada", "ligar_coordenacao"),
    ("deixe a diretoria iluminada", "ligar_coordenacao"),
    ("diretoria luz", "ligar_coordenacao"),
    ("mais luz na diretoria", "ligar_coordenacao"),
    ("clareie a diretoria", "ligar_coordenacao"),
    ("pode ligar a diretoria", "ligar_coordenacao"),
    ("por favor ligue a diretoria", "ligar_coordenacao"),
    ("preciso de luz na diretoria", "ligar_coordenacao"),



    # Apagar coordenação

    ("apaga a coordenação", "apagar_coordenacao"),
    ("apagar coordenação", "apagar_coordenacao"),
    ("apagar a coordenação", "apagar_coordenacao"),
    ("apague a coordenação", "apagar_coordenacao"),
    ("desliga a coordenação", "apagar_coordenacao"),
    ("desligar coordenação", "apagar_coordenacao"),
    ("desligar a coordenação", "apagar_coordenacao"),
    ("desligue a coordenação", "apagar_coordenacao"),
    ("apaga a luz da coordenação", "apagar_coordenacao"),
    ("apague a luz da coordenação", "apagar_coordenacao"),
    ("desliga a luz da coordenação", "apagar_coordenacao"),
    ("desligue a luz da coordenação", "apagar_coordenacao"),
    ("apagar as luzes da coordenação", "apagar_coordenacao"),
    ("apague as luzes da coordenação", "apagar_coordenacao"),
    ("desligar as luzes da coordenação", "apagar_coordenacao"),
    ("desligue as luzes da coordenação", "apagar_coordenacao"),
    ("apaga a iluminação da coordenação", "apagar_coordenacao"),
    ("desliga a iluminação da coordenação", "apagar_coordenacao"),
    ("apagar a iluminação da coordenação", "apagar_coordenacao"),
    ("desligar a iluminação da coordenação", "apagar_coordenacao"),
    ("desative a iluminação da coordenação", "apagar_coordenacao"),
    ("quero apagar a coordenação", "apagar_coordenacao"),
    ("quero a coordenação escura", "apagar_coordenacao"),
    ("deixe a coordenação escura", "apagar_coordenacao"),
    ("sem luz na coordenação", "apagar_coordenacao"),
    ("coordenação sem luz", "apagar_coordenacao"),
    ("retire a iluminação da coordenação", "apagar_coordenacao"),
    ("escureça a coordenação", "apagar_coordenacao"),
    ("pode apagar a coordenação", "apagar_coordenacao"),
    ("por favor apague a coordenação", "apagar_coordenacao"),
    ("apaga a secretaria", "apagar_coordenacao"),
    ("apagar secretaria", "apagar_coordenacao"),
    ("apagar a secretaria", "apagar_coordenacao"),
    ("apague a secretaria", "apagar_coordenacao"),
    ("desliga a secretaria", "apagar_coordenacao"),
    ("desligar secretaria", "apagar_coordenacao"),
    ("desligar a secretaria", "apagar_coordenacao"),
    ("desligue a secretaria", "apagar_coordenacao"),
    ("apaga a luz da secretaria", "apagar_coordenacao"),
    ("apague a luz da secretaria", "apagar_coordenacao"),
    ("desliga a luz da secretaria", "apagar_coordenacao"),
    ("desligue a luz da secretaria", "apagar_coordenacao"),
    ("apagar as luzes da secretaria", "apagar_coordenacao"),
    ("apague as luzes da secretaria", "apagar_coordenacao"),
    ("desligar as luzes da secretaria", "apagar_coordenacao"),
    ("desligue as luzes da secretaria", "apagar_coordenacao"),
    ("apaga a iluminação da secretaria", "apagar_coordenacao"),
    ("desliga a iluminação da secretaria", "apagar_coordenacao"),
    ("apagar a iluminação da secretaria", "apagar_coordenacao"),
    ("desligar a iluminação da secretaria", "apagar_coordenacao"),
    ("desative a iluminação da secretaria", "apagar_coordenacao"),
    ("quero apagar a secretaria", "apagar_coordenacao"),
    ("quero a secretaria escura", "apagar_coordenacao"),
    ("deixe a secretaria escura", "apagar_coordenacao"),
    ("sem luz na secretaria", "apagar_coordenacao"),
    ("secretaria sem luz", "apagar_coordenacao"),
    ("retire a iluminação da secretaria", "apagar_coordenacao"),
    ("escureça a secretaria", "apagar_coordenacao"),
    ("pode apagar a secretaria", "apagar_coordenacao"),
    ("por favor apague a secretaria", "apagar_coordenacao"),
    ("apaga a diretoria", "apagar_coordenacao"),
    ("apagar diretoria", "apagar_coordenacao"),
    ("apagar a diretoria", "apagar_coordenacao"),
    ("apague a diretoria", "apagar_coordenacao"),
    ("desliga a diretoria", "apagar_coordenacao"),
    ("desligar diretoria", "apagar_coordenacao"),
    ("desligar a diretoria", "apagar_coordenacao"),
    ("desligue a diretoria", "apagar_coordenacao"),
    ("apaga a luz da diretoria", "apagar_coordenacao"),
    ("apague a luz da diretoria", "apagar_coordenacao"),
    ("desliga a luz da diretoria", "apagar_coordenacao"),
    ("desligue a luz da diretoria", "apagar_coordenacao"),
    ("apagar as luzes da diretoria", "apagar_coordenacao"),
    ("apague as luzes da diretoria", "apagar_coordenacao"),
    ("desligar as luzes da diretoria", "apagar_coordenacao"),
    ("desligue as luzes da diretoria", "apagar_coordenacao"),
    ("apaga a iluminação da diretoria", "apagar_coordenacao"),
    ("desliga a iluminação da diretoria", "apagar_coordenacao"),
    ("apagar a iluminação da diretoria", "apagar_coordenacao"),
    ("desligar a iluminação da diretoria", "apagar_coordenacao"),
    ("desative a iluminação da diretoria", "apagar_coordenacao"),
    ("quero apagar a diretoria", "apagar_coordenacao"),
    ("quero a diretoria escura", "apagar_coordenacao"),
    ("deixe a diretoria escura", "apagar_coordenacao"),
    ("sem luz na diretoria", "apagar_coordenacao"),
    ("diretoria sem luz", "apagar_coordenacao"),
    ("retire a iluminação da diretoria", "apagar_coordenacao"),
    ("escureça a diretoria", "apagar_coordenacao"),
    ("pode apagar a diretoria", "apagar_coordenacao"),
    ("por favor apague a diretoria", "apagar_coordenacao"),


    # Ligar pátio

    ("acender pátio", "ligar_patio"),
    ("acender pátio", "ligar_patio"),
    ("ligar pátio", "ligar_patio"),
    ("ligue o pátio", "ligar_patio"),
    ("acenda o pátio", "ligar_patio"),
    ("acenda o pátio", "ligar_patio"),
    ("ligar a luz do pátio", "ligar_patio"),
    ("acender a luz do pátio", "ligar_patio"),
    ("acender a luz do pátio", "ligar_patio"),
    ("ligue a luz do pátio", "ligar_patio"),
    ("acenda a luz do pátio", "ligar_patio"),
    ("quero a luz do pátio ligada", "ligar_patio"),
    ("deixe a luz do pátio acesa", "ligar_patio"),
    ("ilumine o pátio", "ligar_patio"),
    ("coloque luz no pátio", "ligar_patio"),
    ("liga o pátio", "ligar_patio"),
    ("acende o pátio", "ligar_patio"),
    ("acende o pátio", "ligar_patio"),
    ("liga a luz do pátio", "ligar_patio"),
    ("acende a luz do pátio", "ligar_patio"),
    ("acende a luz do pátio", "ligar_patio"),
    ("pode ligar o pátio", "ligar_patio"),
    ("pode acender o pátio", "ligar_patio"),
    ("pode ligar a luz do pátio", "ligar_patio"),
    ("por favor ligue o pátio", "ligar_patio"),
    ("por favor acenda o pátio", "ligar_patio"),
    ("por favor ligue a luz do pátio", "ligar_patio"),
    ("gostaria de ligar o pátio", "ligar_patio"),
    ("gostaria que acendesse o pátio", "ligar_patio"),
    ("ative a iluminação do pátio", "ligar_patio"),
    ("ative as luzes do pátio", "ligar_patio"),
    ("ligue as luzes do pátio", "ligar_patio"),
    ("acenda as luzes do pátio", "ligar_patio"),
    ("ilumine a área do pátio", "ligar_patio"),
    ("deixe o pátio iluminado", "ligar_patio"),
    ("quero iluminar o pátio", "ligar_patio"),
    ("liga a iluminação do pátio", "ligar_patio"),
    ("acende a iluminação do pátio", "ligar_patio"),
    ("quero o pátio iluminado", "ligar_patio"),
    ("coloque o pátio na iluminação", "ligar_patio"),
    ("coloque as luzes do pátio para funcionar", "ligar_patio"),
    ("ligar iluminação do pátio", "ligar_patio"),
    ("acender iluminação do pátio", "ligar_patio"),
    ("luz do pátio ligada", "ligar_patio"),
    ("pátio iluminado", "ligar_patio"),


    # Apagar pátio

    ("apagar pátio", "apaga_patio"),
    ("desligar pátio", "apaga_patio"),
    ("apague o pátio", "apaga_patio"),
    ("desligue o pátio", "apaga_patio"),
    ("apagar a luz do pátio", "apaga_patio"),
    ("desligar a luz do pátio", "apaga_patio"),
    ("apague a luz do pátio", "apaga_patio"),
    ("desligue a luz do pátio", "apaga_patio"),
    ("quero a luz do pátio apagada", "apaga_patio"),
    ("deixe a luz do pátio apagada", "apaga_patio"),
    ("escureça o pátio", "apaga_patio"),
    ("apaga o pátio", "apaga_patio"),
    ("desliga o pátio", "apaga_patio"),
    ("apaga a luz do pátio", "apaga_patio"),
    ("desliga a luz do pátio", "apaga_patio"),
    ("pode apagar o pátio", "apaga_patio"),
    ("pode desligar o pátio", "apaga_patio"),
    ("pode apagar a luz do pátio", "apaga_patio"),
    ("por favor apague o pátio", "apaga_patio"),
    ("por favor desligue o pátio", "apaga_patio"),
    ("por favor apague a luz do pátio", "apaga_patio"),
    ("gostaria de apagar o pátio", "apaga_patio"),
    ("gostaria que apagasse o pátio", "apaga_patio"),
    ("desative a iluminação do pátio", "apaga_patio"),
    ("desative as luzes do pátio", "apaga_patio"),
    ("desligue as luzes do pátio", "apaga_patio"),
    ("apague as luzes do pátio", "apaga_patio"),
    ("deixe o pátio escuro", "apaga_patio"),
    ("quero apagar o pátio", "apaga_patio"),
    ("desliga a iluminação do pátio", "apaga_patio"),
    ("apaga a iluminação do pátio", "apaga_patio"),
    ("quero o pátio escuro", "apaga_patio"),
    ("desligar iluminação do pátio", "apaga_patio"),
    ("apagar iluminação do pátio", "apaga_patio"),
    ("luz do pátio apagada", "apaga_patio"),
    ("pátio escuro", "apaga_patio"),
    ("desligue tudo no pátio", "apaga_patio"),
    ("apague tudo no pátio", "apaga_patio"),
    ("desligue todas as luzes do pátio", "apaga_patio"),
    ("apague todas as luzes do pátio", "apaga_patio"),


    #Comandos para desligar as luzes

    ("apague as luzes", "apagar_luz"),
    ("desligue as luzes", "apagar_luz"),
    ("apagar as luzes", "apagar_luz"),
    ("desligar as luzes", "apagar_luz"),
    ("apaga as luzes", "apagar_luz"),
    ("desliga as luzes", "apagar_luz"),
    ("apague a luz", "apagar_luz"),
    ("desligue a luz", "apagar_luz"),
    ("apagar a luz", "apagar_luz"),
    ("desligar a luz", "apagar_luz"),
    ("apaga a luz", "apagar_luz"),
    ("desliga a luz", "apagar_luz"),
    ("apagar luz", "apagar_luz"),
    ("desligar luz", "apagar_luz"),
    ("apague todas as luzes", "apagar_luz"),
    ("desligue todas as luzes", "apagar_luz"),
    ("apagar todas as luzes", "apagar_luz"),
    ("desligar todas as luzes", "apagar_luz"),
    ("apaga todas as luzes", "apagar_luz"),
    ("desliga todas as luzes", "apagar_luz"),
    ("apague toda a iluminação", "apagar_luz"),
    ("desligue toda a iluminação", "apagar_luz"),
    ("apagar toda a iluminação", "apagar_luz"),
    ("desligar toda a iluminação", "apagar_luz"),
    ("apague a iluminação", "apagar_luz"),
    ("desligue a iluminação", "apagar_luz"),
    ("apagar a iluminação", "apagar_luz"),
    ("desligar a iluminação", "apagar_luz"),
    ("desative a iluminação", "apagar_luz"),
    ("desative todas as luzes", "apagar_luz"),
    ("desative o sistema de iluminação", "apagar_luz"),
    ("desligue o sistema de iluminação", "apagar_luz"),
    ("apague as luzes da escola", "apagar_luz"),
    ("desligue as luzes da escola", "apagar_luz"),
    ("apagar as luzes da escola", "apagar_luz"),
    ("desligar as luzes da escola", "apagar_luz"),
    ("apague toda a escola", "apagar_luz"),
    ("desligue toda a escola", "apagar_luz"),
    ("deixe a escola escura", "apagar_luz"),
    ("escureça a escola", "apagar_luz"),
    ("escureça todos os ambientes", "apagar_luz"),
    ("deixe tudo escuro", "apagar_luz"),
    ("apague tudo", "apagar_luz"),
    ("desligue tudo", "apagar_luz"),
    ("apague tudo que é luz", "apagar_luz"),
    ("desligue tudo que é luz", "apagar_luz"),
    ("sem luz", "apagar_luz"),
    ("quero sem luz", "apagar_luz"),
    ("quero todas as luzes apagadas", "apagar_luz"),
    ("quero a escola escura", "apagar_luz"),
    ("não preciso mais de luz", "apagar_luz"),
    ("retire toda a iluminação", "apagar_luz"),
    ("corte a iluminação", "apagar_luz"),
    ("pare a iluminação", "apagar_luz"),
    ("interrompa a iluminação", "apagar_luz"),
    ("encerre as luzes", "apagar_luz"),
    ("encerre a iluminação", "apagar_luz"),
    ("finalize a iluminação", "apagar_luz"),
    ("desative as luzes", "apagar_luz"),
    ("desative a luz", "apagar_luz"),
    ("desligue as lâmpadas", "apagar_luz"),
    ("apague as lâmpadas", "apagar_luz"),
    ("desligue todas as lâmpadas", "apagar_luz"),
    ("apague todas as lâmpadas", "apagar_luz"),
    ("apague as luzes internas", "apagar_luz"),
    ("desligue as luzes internas", "apagar_luz"),
    ("apague toda a iluminação da escola", "apagar_luz"),
    ("desligue toda a iluminação da escola", "apagar_luz"),
    ("desligar iluminação geral", "apagar_luz"),
    ("apagar iluminação geral", "apagar_luz"),
    ("desligue a iluminação geral", "apagar_luz"),
    ("apague a iluminação geral", "apagar_luz"),
    ("desligue todas as salas", "apagar_luz"),
    ("apague todas as salas", "apagar_luz"),
    ("deixe todas as salas escuras", "apagar_luz"),
    ("quero apagar todas as luzes", "apagar_luz"),
    ("quero desligar todas as luzes", "apagar_luz"),
    ("por favor apague as luzes", "apagar_luz"),
    ("por favor desligue as luzes", "apagar_luz"),
    ("pode apagar as luzes", "apagar_luz"),
    ("pode desligar as luzes", "apagar_luz"),
    ("não deixe nenhuma luz acesa", "apagar_luz"),
    ("apague todas as luzes do prédio", "apagar_luz"),
    ("desligue todas as luzes do prédio", "apagar_luz"),
    ("desligue a iluminação completa", "apagar_luz"),
    ("apague a iluminação completa", "apagar_luz"),
    ("desligar tudo", "apagar_luz"),
    ("apagar tudo na escola", "apagar_luz"),


    #Comandos para ligar luzes da quadra

    ("ligar luzes da quadra", "ligar_quadra"),
    ("ligar a quadra", "ligar_quadra"),
    ("ligar quadra", "ligar_quadra"),
    ("ligue a quadra", "ligar_quadra"),
    ("liga a quadra", "ligar_quadra"),
    ("luzes da quadra", "ligar_quadra"),
    ("luzes quadra", "ligar_quadra"),
    ("luz da quadra", "ligar_quadra"),
    ("ligar a luz da quadra", "ligar_quadra"),
    ("ligue a luz da quadra", "ligar_quadra"),
    ("liga a luz da quadra", "ligar_quadra"),
    ("acenda luzes da quadra", "ligar_quadra"),
    ("acender luzes da quadra", "ligar_quadra"),
    ("acenda as luzes da quadra", "ligar_quadra"),
    ("acender as luzes da quadra", "ligar_quadra"),
    ("acende as luzes da quadra", "ligar_quadra"),
    ("acender quadra", "ligar_quadra"),
    ("acende a quadra", "ligar_quadra"),
    ("acenda a quadra", "ligar_quadra"),
    ("ilumine a quadra", "ligar_quadra"),
    ("ilumina a quadra", "ligar_quadra"),
    ("ligar iluminação da quadra", "ligar_quadra"),
    ("ligar a iluminação da quadra", "ligar_quadra"),
    ("ligue a iluminação da quadra", "ligar_quadra"),
    ("acender a iluminação da quadra", "ligar_quadra"),
    ("acenda a iluminação da quadra", "ligar_quadra"),
    ("ative a iluminação da quadra", "ligar_quadra"),
    ("ativar iluminação da quadra", "ligar_quadra"),
    ("ative as luzes da quadra", "ligar_quadra"),
    ("quero luz na quadra", "ligar_quadra"),
    ("quero a quadra iluminada", "ligar_quadra"),
    ("deixe a quadra iluminada", "ligar_quadra"),
    ("clareie a quadra", "ligar_quadra"),
    ("mais luz na quadra", "ligar_quadra"),
    ("coloque luz na quadra", "ligar_quadra"),
    ("ligue os refletores da quadra", "ligar_quadra"),
    ("liga os refletores da quadra", "ligar_quadra"),
    ("acenda os refletores da quadra", "ligar_quadra"),
    ("acender os refletores da quadra", "ligar_quadra"),
    ("ligue as luzes do ginásio", "ligar_quadra"),
    ("liga as luzes do ginásio", "ligar_quadra"),
    ("acenda as luzes do ginásio", "ligar_quadra"),
    ("ilumine o ginásio", "ligar_quadra"),
    ("ligar iluminação do ginásio", "ligar_quadra"),
    ("preciso de luz na quadra", "ligar_quadra"),
    ("pode ligar a quadra", "ligar_quadra"),
    ("por favor ligue a quadra", "ligar_quadra"),
    ("gostaria de ligar a quadra", "ligar_quadra"),
    ("ligue somente a quadra", "ligar_quadra"),
    ("acenda somente a quadra", "ligar_quadra"),
    ("ligue apenas a quadra", "ligar_quadra"),
    ("acenda apenas a quadra", "ligar_quadra"),
    ("prepare a quadra", "ligar_quadra"),
    ("deixe a quadra pronta", "ligar_quadra"),
    ("ligar iluminação esportiva", "ligar_quadra"),
    ("acender iluminação esportiva", "ligar_quadra"),
    ("acione as luzes da quadra", "ligar_quadra"),
    ("acione a iluminação da quadra", "ligar_quadra"),
    ("coloque a quadra em funcionamento", "ligar_quadra"),
    ("ilumine a área da quadra", "ligar_quadra"),
    ("ligar a área da quadra", "ligar_quadra"),
    ("acender a área da quadra", "ligar_quadra"),


    #Comandos para desligar as luzes da quadra

    ("desliga tudo na quadra", "apagar_quadra"),
    ("apagar quadra", "apagar_quadra"),
    ("apaga a quadra", "apagar_quadra"),
    ("apagar a quadra", "apagar_quadra"),
    ("apague a quadra", "apagar_quadra"),
    ("desligar quadra", "apagar_quadra"),
    ("desliga a quadra", "apagar_quadra"),
    ("desligar a quadra", "apagar_quadra"),
    ("desligue a quadra", "apagar_quadra"),
    ("apagar luzes da quadra", "apagar_quadra"),
    ("apague luzes da quadra", "apagar_quadra"),
    ("apagar as luzes da quadra", "apagar_quadra"),
    ("apague as luzes da quadra", "apagar_quadra"),
    ("desligar luzes da quadra", "apagar_quadra"),
    ("desligue luzes da quadra", "apagar_quadra"),
    ("desligar as luzes da quadra", "apagar_quadra"),
    ("desligue as luzes da quadra", "apagar_quadra"),
    ("apagar a luz da quadra", "apagar_quadra"),
    ("apague a luz da quadra", "apagar_quadra"),
    ("desligar a luz da quadra", "apagar_quadra"),
    ("desligue a luz da quadra", "apagar_quadra"),
    ("encerrar quadra", "apagar_quadra"),
    ("encerre a quadra", "apagar_quadra"),
    ("encerrar iluminação da quadra", "apagar_quadra"),
    ("encerre a iluminação da quadra", "apagar_quadra"),
    ("desligar iluminação da quadra", "apagar_quadra"),
    ("desliga a iluminação da quadra", "apagar_quadra"),
    ("desligar a iluminação da quadra", "apagar_quadra"),
    ("desligue a iluminação da quadra", "apagar_quadra"),
    ("apagar iluminação da quadra", "apagar_quadra"),
    ("apaga a iluminação da quadra", "apagar_quadra"),
    ("apagar a iluminação da quadra", "apagar_quadra"),
    ("apague a iluminação da quadra", "apagar_quadra"),
    ("desative a iluminação da quadra", "apagar_quadra"),
    ("desative as luzes da quadra", "apagar_quadra"),
    ("quero apagar a quadra", "apagar_quadra"),
    ("quero a quadra escura", "apagar_quadra"),
    ("deixe a quadra escura", "apagar_quadra"),
    ("sem luz na quadra", "apagar_quadra"),
    ("quadra sem luz", "apagar_quadra"),
    ("retire a iluminação da quadra", "apagar_quadra"),
    ("escureça a quadra", "apagar_quadra"),
    ("desligue os refletores da quadra", "apagar_quadra"),
    ("desliga os refletores da quadra", "apagar_quadra"),
    ("apague os refletores da quadra", "apagar_quadra"),
    ("apaga os refletores da quadra", "apagar_quadra"),
    ("desligue as luzes do ginásio", "apagar_quadra"),
    ("desliga as luzes do ginásio", "apagar_quadra"),
    ("apague as luzes do ginásio", "apagar_quadra"),
    ("apaga as luzes do ginásio", "apagar_quadra"),
    ("escureça o ginásio", "apagar_quadra"),
    ("desligue somente a quadra", "apagar_quadra"),
    ("apague somente a quadra", "apagar_quadra"),
    ("desligue apenas a quadra", "apagar_quadra"),
    ("apague apenas a quadra", "apagar_quadra"),
    ("desligue tudo da quadra", "apagar_quadra"),
    ("apague tudo da quadra", "apagar_quadra"),
    ("pode apagar a quadra", "apagar_quadra"),
    ("por favor apague a quadra", "apagar_quadra"),
    ("gostaria de apagar a quadra", "apagar_quadra"),
    ("não preciso mais de luz na quadra", "apagar_quadra"),
    ("finalize a iluminação da quadra", "apagar_quadra"),
    ("desative o sistema de iluminação da quadra", "apagar_quadra"),



    # Abrir portão principal
    ("abrir portão", "abrir_portao"),
    ("abrir o portão", "abrir_portao"),
    ("abrir portão de entrada", "abrir_portao"),
    ("abrir o portão de entrada", "abrir_portao"),
    ("abrir o portão da escola", "abrir_portao"),
    ("abrir portão da escola", "abrir_portao"),
    ("abra o portão", "abrir_portao"),
    ("abra o portão da escola", "abrir_portao"),
    ("abra o portão de entrada", "abrir_portao"),
    ("abre o portão", "abrir_portao"),
    ("abre o portão da escola", "abrir_portao"),
    ("abre o portão de entrada", "abrir_portao"),
    ("abre o portão principal", "abrir_portao"),
    ("abra o portão principal", "abrir_portao"),
    ("abrir portão principal", "abrir_portao"),
    ("ligue o portão", "abrir_portao"),
    ("acione o portão", "abrir_portao"),
    ("ative o portão", "abrir_portao"),
    ("libere o portão", "abrir_portao"),
    ("libere a entrada", "abrir_portao"),
    ("libere o acesso", "abrir_portao"),
    ("pode abrir o portão", "abrir_portao"),
    ("pode abrir o portão da escola", "abrir_portao"),
    ("por favor abra o portão", "abrir_portao"),
    ("por favor abra o portão da escola", "abrir_portao"),
    ("por favor abra o portão principal", "abrir_portao"),
    ("quero abrir o portão", "abrir_portao"),
    ("gostaria de abrir o portão", "abrir_portao"),
    ("gostaria que abrisse o portão", "abrir_portao"),
    ("abra a entrada da escola", "abrir_portao"),
    ("abra a entrada principal", "abrir_portao"),
    ("libere a entrada principal", "abrir_portao"),
    ("abra o acesso da escola", "abrir_portao"),
    ("libere o acesso da escola", "abrir_portao"),
    ("destrave o portão", "abrir_portao"),
    ("destrave o portão da escola", "abrir_portao"),
    ("destrave a entrada", "abrir_portao"),
    ("destrancar o portão", "abrir_portao"),
    ("destrancar o portão da escola", "abrir_portao"),
    ("abrir entrada", "abrir_portao"),
    ("abrir acesso", "abrir_portao"),
    ("abrir acesso da escola", "abrir_portao"),
    ("abra o portão para mim", "abrir_portao"),
    ("abra o portão de acesso", "abrir_portao"),
    ("abrir o portão de acesso", "abrir_portao"),
    ("libere o portão principal", "abrir_portao"),
    ("acione o portão principal", "abrir_portao"),
    ("ative o portão principal", "abrir_portao"),
    ("quero o portão aberto", "abrir_portao"),
    ("deixe o portão aberto", "abrir_portao"),
    ("abra a entrada para mim", "abrir_portao"),
    ("abrir o portão agora", "abrir_portao"),
    ("abra o portão agora", "abrir_portao"),
    ("abre o portão agora", "abrir_portao"),
    ("quero que abra o portão", "abrir_portao"),
    ("abra imediatamente o portão", "abrir_portao"),
    ("abra o portão de entrada da escola", "abrir_portao"),
    ("abrir o portão de entrada da escola", "abrir_portao"),
    ("abre o portão de entrada da escola", "abrir_portao"),


    # Fechar portão principal

    ("fechar o portão", "fechar_portao"),
    ("fechar portão", "fechar_portao"),
    ("fechar o portão da escola", "fechar_portao"),
    ("fechar o portão de entrada", "fechar_portao"),
    ("fechar o portão principal", "fechar_portao"),
    ("feche o portão", "fechar_portao"),
    ("feche o portão da escola", "fechar_portao"),
    ("feche o portão principal", "fechar_portao"),
    ("feche o portão de entrada", "fechar_portao"),
    ("fecha o portão", "fechar_portao"),
    ("fecha o portão da escola", "fechar_portao"),
    ("fecha o portão principal", "fechar_portao"),
    ("fecha o portão de entrada", "fechar_portao"),
    ("encerre a entrada da escola", "fechar_portao"),
    ("encerre o acesso principal", "fechar_portao"),
    ("bloqueie a entrada da escola", "fechar_portao"),
    ("bloqueie o acesso da escola", "fechar_portao"),
    ("tranque o portão", "fechar_portao"),
    ("tranque o portão da escola", "fechar_portao"),
    ("trancar o portão", "fechar_portao"),
    ("trancar o portão da escola", "fechar_portao"),
    ("trave o portão", "fechar_portao"),
    ("trave o portão principal", "fechar_portao"),
    ("trave a entrada", "fechar_portao"),
    ("bloqueie o portão principal", "fechar_portao"),
    ("interrompa a entrada", "fechar_portao"),
    ("interrompa o acesso", "fechar_portao"),
    ("desative o acesso da escola", "fechar_portao"),
    ("desative a entrada principal", "fechar_portao"),
    ("pode fechar o portão", "fechar_portao"),
    ("pode fechar o portão da escola", "fechar_portao"),
    ("por favor feche o portão", "fechar_portao"),
    ("por favor feche o portão principal", "fechar_portao"),
    ("por favor feche o portão de entrada", "fechar_portao"),
    ("gostaria de fechar o portão", "fechar_portao"),
    ("gostaria que fechasse o portão", "fechar_portao"),
    ("quero fechar o portão", "fechar_portao"),
    ("quero que o portão seja fechado", "fechar_portao"),
    ("preciso fechar o portão", "fechar_portao"),
    ("deixe o portão fechado", "fechar_portao"),
    ("mantenha o portão fechado", "fechar_portao"),
    ("impedir novas entradas", "fechar_portao"),
    ("pare o acesso à escola", "fechar_portao"),
    ("suspenda a entrada", "fechar_portao"),
    ("suspenda o acesso principal", "fechar_portao"),
    ("feche a entrada da escola", "fechar_portao"),
    ("feche a entrada principal", "fechar_portao"),
    ("feche o acesso da escola", "fechar_portao"),
    ("feche o acesso principal", "fechar_portao"),
    ("isole a entrada da escola", "fechar_portao"),
    ("isole o acesso principal", "fechar_portao"),
    ("ative o fechamento do portão", "fechar_portao"),
    ("inicie o fechamento do portão", "fechar_portao"),
    ("execute o fechamento do portão", "fechar_portao"),
    ("fechar entrada", "fechar_portao"),
    ("fechar acesso", "fechar_portao"),
    ("fechar acesso da escola", "fechar_portao"),
    ("fechar portão agora", "fechar_portao"),
    ("feche o portão agora", "fechar_portao"),
    ("fecha o portão agora", "fechar_portao"),
    ("feche imediatamente o portão", "fechar_portao"),
    ("quero o portão fechado", "fechar_portao"),
    ("feche os portões da escola", "fechar_portao"),
    ("já pode fechar o portão", "fechar_portao"),
    ("é hora de fechar o portão", "fechar_portao"),
    ("finalize o acesso à escola", "fechar_portao"),
    ("desabilite a entrada da escola", "fechar_portao"),
    ("impeça a entrada de visitantes", "fechar_portao"),
    ("feche o portão de entrada da escola", "fechar_portao"),
    ("fecha o portão de entrada da escola", "fechar_portao"),
    ("feche completamente o portão", "fechar_portao"),
    ("garanta que o portão fique fechado", "fechar_portao"),
    ("feche e trave o portão", "fechar_portao"),
    ("tranque a entrada principal", "fechar_portao"),


    # Abrir porta da coordenação

    ("abrir a porta da coordenação", "abrir_coord"),
    ("abrir porta da coordenação", "abrir_coord"),
    ("abra a porta da coordenação", "abrir_coord"),
    ("abre a porta da coordenação", "abrir_coord"),
    ("abrir a sala da coordenação", "abrir_coord"),
    ("abra a sala da coordenação", "abrir_coord"),
    ("libere a coordenação", "abrir_coord"),
    ("libere a porta da coordenação", "abrir_coord"),
    ("destranque a porta da coordenação", "abrir_coord"),
    ("destrancar a porta da coordenação", "abrir_coord"),
    ("pode abrir a coordenação", "abrir_coord"),
    ("por favor abra a coordenação", "abrir_coord"),
    ("quero abrir a coordenação", "abrir_coord"),
    ("preciso entrar na coordenação", "abrir_coord"),
    ("abra a coordenação", "abrir_coord"),
    ("abre a coordenação", "abrir_coord"),
    ("abrir a porta da diretoria", "abrir_coord"),
    ("abrir porta da diretoria", "abrir_coord"),
    ("abra a porta da diretoria", "abrir_coord"),
    ("abre a porta da diretoria", "abrir_coord"),
    ("abrir a sala da diretoria", "abrir_coord"),
    ("abra a sala da diretoria", "abrir_coord"),
    ("libere a diretoria", "abrir_coord"),
    ("libere a porta da diretoria", "abrir_coord"),
    ("destranque a porta da diretoria", "abrir_coord"),
    ("destrancar a porta da diretoria", "abrir_coord"),
    ("pode abrir a diretoria", "abrir_coord"),
    ("por favor abra a diretoria", "abrir_coord"),
    ("quero abrir a diretoria", "abrir_coord"),
    ("preciso entrar na diretoria", "abrir_coord"),
    ("abra a diretoria", "abrir_coord"),
    ("abre a diretoria", "abrir_coord"),
    ("abrir a porta da secretaria", "abrir_coord"),
    ("abrir porta da secretaria", "abrir_coord"),
    ("abra a porta da secretaria", "abrir_coord"),
    ("abre a porta da secretaria", "abrir_coord"),
    ("abrir a sala da secretaria", "abrir_coord"),
    ("abra a sala da secretaria", "abrir_coord"),
    ("libere a secretaria", "abrir_coord"),
    ("libere a porta da secretaria", "abrir_coord"),
    ("destranque a porta da secretaria", "abrir_coord"),
    ("destrancar a porta da secretaria", "abrir_coord"),
    ("pode abrir a secretaria", "abrir_coord"),
    ("por favor abra a secretaria", "abrir_coord"),
    ("quero abrir a secretaria", "abrir_coord"),
    ("preciso entrar na secretaria", "abrir_coord"),
    ("abra a secretaria", "abrir_coord"),
    ("abre a secretaria", "abrir_coord"),
    ("abra a porta da coordenação para mim", "abrir_coord"),
    ("abra a porta da diretoria para mim", "abrir_coord"),
    ("abra a porta da secretaria para mim", "abrir_coord"),
    ("libere o acesso à coordenação", "abrir_coord"),
    ("libere o acesso à diretoria", "abrir_coord"),
    ("libere o acesso à secretaria", "abrir_coord"),
    ("quero acessar a coordenação", "abrir_coord"),
    ("quero acessar a diretoria", "abrir_coord"),
    ("quero acessar a secretaria", "abrir_coord"),
    ("desbloqueie a porta da coordenação", "abrir_coord"),
    ("desbloqueie a porta da diretoria", "abrir_coord"),
    ("desbloqueie a porta da secretaria", "abrir_coord"),
    ("abra a entrada da coordenação", "abrir_coord"),
    ("abra a entrada da diretoria", "abrir_coord"),
    ("abra a entrada da secretaria", "abrir_coord"),
    ("libere minha entrada na coordenação", "abrir_coord"),
    ("libere minha entrada na diretoria", "abrir_coord"),
    ("libere minha entrada na secretaria", "abrir_coord"),
    ("preciso acessar a coordenação", "abrir_coord"),
    ("preciso acessar a diretoria", "abrir_coord"),
    ("preciso acessar a secretaria", "abrir_coord"),
    ("abra imediatamente a porta da coordenação", "abrir_coord"),
    ("abra imediatamente a porta da diretoria", "abrir_coord"),
    ("abra imediatamente a porta da secretaria", "abrir_coord"),
    ("abrir coordenação", "abrir_coord"),
    ("abrir diretoria", "abrir_coord"),
    ("abrir secretaria", "abrir_coord"),
    ("abrir a porta do setor da coordenação", "abrir_coord"),
    ("abrir a porta do setor da diretoria", "abrir_coord"),
    ("abrir a porta do setor da secretaria", "abrir_coord"),


    # Fechar porta da coordenação

    ("fechar a porta da coordenação", "fechar_coord"),
    ("fechar porta da coordenação", "fechar_coord"),
    ("feche a porta da coordenação", "fechar_coord"),
    ("fecha a porta da coordenação", "fechar_coord"),
    ("fechar a sala da coordenação", "fechar_coord"),
    ("feche a sala da coordenação", "fechar_coord"),
    ("tranque a porta da coordenação", "fechar_coord"),
    ("trancar a porta da coordenação", "fechar_coord"),
    ("trave a porta da coordenação", "fechar_coord"),
    ("bloqueie a porta da coordenação", "fechar_coord"),
    ("encerre o acesso à coordenação", "fechar_coord"),
    ("feche a coordenação", "fechar_coord"),
    ("fecha a coordenação", "fechar_coord"),
    ("quero fechar a coordenação", "fechar_coord"),
    ("por favor feche a coordenação", "fechar_coord"),
    ("deixe a coordenação fechada", "fechar_coord"),
    ("fechar a porta da diretoria", "fechar_coord"),
    ("fechar porta da diretoria", "fechar_coord"),
    ("feche a porta da diretoria", "fechar_coord"),
    ("fecha a porta da diretoria", "fechar_coord"),
    ("fechar a sala da diretoria", "fechar_coord"),
    ("feche a sala da diretoria", "fechar_coord"),
    ("tranque a porta da diretoria", "fechar_coord"),
    ("trancar a porta da diretoria", "fechar_coord"),
    ("trave a porta da diretoria", "fechar_coord"),
    ("bloqueie a porta da diretoria", "fechar_coord"),
    ("encerre o acesso à diretoria", "fechar_coord"),
    ("feche a diretoria", "fechar_coord"),
    ("fecha a diretoria", "fechar_coord"),
    ("quero fechar a diretoria", "fechar_coord"),
    ("por favor feche a diretoria", "fechar_coord"),
    ("deixe a diretoria fechada", "fechar_coord"),
    ("fechar a porta da secretaria", "fechar_coord"),
    ("fechar porta da secretaria", "fechar_coord"),
    ("feche a porta da secretaria", "fechar_coord"),
    ("fecha a porta da secretaria", "fechar_coord"),
    ("fechar a sala da secretaria", "fechar_coord"),
    ("feche a sala da secretaria", "fechar_coord"),
    ("tranque a porta da secretaria", "fechar_coord"),
    ("trancar a porta da secretaria", "fechar_coord"),
    ("trave a porta da secretaria", "fechar_coord"),
    ("bloqueie a porta da secretaria", "fechar_coord"),
    ("encerre o acesso à secretaria", "fechar_coord"),
    ("feche a secretaria", "fechar_coord"),
    ("fecha a secretaria", "fechar_coord"),
    ("quero fechar a secretaria", "fechar_coord"),
    ("por favor feche a secretaria", "fechar_coord"),
    ("deixe a secretaria fechada", "fechar_coord"),
    ("feche a porta da coordenação para mim", "fechar_coord"),
    ("feche a porta da diretoria para mim", "fechar_coord"),
    ("feche a porta da secretaria para mim", "fechar_coord"),
    ("bloqueie o acesso à coordenação", "fechar_coord"),
    ("bloqueie o acesso à diretoria", "fechar_coord"),
    ("bloqueie o acesso à secretaria", "fechar_coord"),
    ("não permita entrada na coordenação", "fechar_coord"),
    ("não permita entrada na diretoria", "fechar_coord"),
    ("não permita entrada na secretaria", "fechar_coord"),
    ("impeça o acesso à coordenação", "fechar_coord"),
    ("impeça o acesso à diretoria", "fechar_coord"),
    ("impeça o acesso à secretaria", "fechar_coord"),
    ("feche a entrada da coordenação", "fechar_coord"),
    ("feche a entrada da diretoria", "fechar_coord"),
    ("feche a entrada da secretaria", "fechar_coord"),
    ("tranque a coordenação", "fechar_coord"),
    ("tranque a diretoria", "fechar_coord"),
    ("tranque a secretaria", "fechar_coord"),
    ("feche completamente a coordenação", "fechar_coord"),
    ("feche completamente a diretoria", "fechar_coord"),
    ("feche completamente a secretaria", "fechar_coord"),
    ("garanta que a coordenação fique fechada", "fechar_coord"),
    ("garanta que a diretoria fique fechada", "fechar_coord"),
    ("garanta que a secretaria fique fechada", "fechar_coord"),
    ("feche e tranque a coordenação", "fechar_coord"),
    ("feche e tranque a diretoria", "fechar_coord"),
    ("feche e tranque a secretaria", "fechar_coord"),
    ("fechar coordenação", "fechar_coord"),
    ("fechar diretoria", "fechar_coord"),
    ("fechar secretaria", "fechar_coord"),
    ("já pode fechar a coordenação", "fechar_coord"),
    ("já pode fechar a diretoria", "fechar_coord"),
    ("já pode fechar a secretaria", "fechar_coord"),
    ("é hora de fechar a coordenação", "fechar_coord"),
    ("é hora de fechar a diretoria", "fechar_coord"),
    ("é hora de fechar a secretaria", "fechar_coord"),



    #Comando para a realizar chamada

    ("realize a chamada", "fazer_chamada"),
    ("realizar chamada", "fazer_chamada"),
    ("realizar a chamada", "fazer_chamada"),
    ("faça a chamada", "fazer_chamada"),
    ("fazer chamada", "fazer_chamada"),
    ("fazer a chamada", "fazer_chamada"),
    ("iniciar chamada", "fazer_chamada"),
    ("inicie a chamada", "fazer_chamada"),
    ("iniciar a chamada", "fazer_chamada"),
    ("começar a chamada", "fazer_chamada"),
    ("comece a chamada", "fazer_chamada"),
    ("dar início à chamada", "fazer_chamada"),
    ("registre a presença", "fazer_chamada"),
    ("registrar presença", "fazer_chamada"),
    ("registrar a presença", "fazer_chamada"),
    ("registre as presenças", "fazer_chamada"),
    ("registrar as presenças", "fazer_chamada"),
    ("marcar presença", "fazer_chamada"),
    ("marque presença", "fazer_chamada"),
    ("marcar as presenças", "fazer_chamada"),
    ("marque as presenças", "fazer_chamada"),
    ("registrar frequência", "fazer_chamada"),
    ("registre a frequência", "fazer_chamada"),
    ("registrar frequência da turma", "fazer_chamada"),
    ("registre a frequência da turma", "fazer_chamada"),
    ("fazer lista de presença", "fazer_chamada"),
    ("faça a lista de presença", "fazer_chamada"),
    ("iniciar lista de presença", "fazer_chamada"),
    ("começar lista de presença", "fazer_chamada"),
    ("abrir chamada", "fazer_chamada"),
    ("abra a chamada", "fazer_chamada"),
    ("abrir a chamada", "fazer_chamada"),
    ("abrir lista de presença", "fazer_chamada"),
    ("inicie o registro de presença", "fazer_chamada"),
    ("comece o registro de presença", "fazer_chamada"),
    ("preciso fazer a chamada", "fazer_chamada"),
    ("quero fazer a chamada", "fazer_chamada"),
    ("quero registrar a presença", "fazer_chamada"),
    ("vamos fazer a chamada", "fazer_chamada"),
    ("vamos registrar a presença", "fazer_chamada"),
    ("hora da chamada", "fazer_chamada"),
    ("hora de fazer a chamada", "fazer_chamada"),
    ("pode fazer a chamada", "fazer_chamada"),
    ("por favor faça a chamada", "fazer_chamada"),
    ("por favor registre a presença", "fazer_chamada"),
    ("realize a lista de presença", "fazer_chamada"),
    ("inicie a lista de presença", "fazer_chamada"),
    ("efetue a chamada", "fazer_chamada"),
    ("efetuar chamada", "fazer_chamada"),
    ("efetue o registro de presença", "fazer_chamada"),
    ("registre quem está presente", "fazer_chamada"),
    ("marque quem está presente", "fazer_chamada"),
    ("verifique a presença dos alunos", "fazer_chamada"),
    ("confira a presença dos alunos", "fazer_chamada"),
    ("registre a frequência dos alunos", "fazer_chamada"),
    ("inicie a conferência de presença", "fazer_chamada"),
    ("comece a conferência de presença", "fazer_chamada"),
    ("fazer controle de presença", "fazer_chamada"),
    ("iniciar controle de presença", "fazer_chamada"),
    ("registre os alunos presentes", "fazer_chamada"),



    #Comandos para consultar o aluno (série,presença,boletim e etc)

    ("consulta o aluno","consultar_aluno"),
    ("consulte o aluno", "consultar_aluno"),
    ("busque o aluno", "consultar_aluno"),
    ("informações sobre o aluno", "consultar_aluno"),
    ("busque o estudante", "consultar_aluno"),
    ("informações sobre o estudante", "consultar_aluno"),
    ("dados do aluno", "consultar_aluno"),
    ("dados do estudante", "consultar_aluno"),
    ("pesquise aluno", "consultar_aluno"),
    ("pesquise estudante","consultar_aluno"),

    #Saudação

    ("oi tudo bem", "saudacao"),
    ("olá", "saudacao"),
    ("ola", "saudacao"),
    ("oi", "saudacao"),
    ("tudo bem", "saudacao"),
    ("tudo certo", "saudacao"),
    ("como vai", "saudacao"),
    ("como você está", "saudacao"),
    ("bom dia", "saudacao"),
    ("boa tarde", "saudacao"),
    ("boa noite", "saudacao"),
    ("Olá ia", "saudacao"),
    ("ola ia", "saudacao"),
    ("oi ia", "saudacao"),
    ("eai", "saudacao"),
    ("e aí", "saudacao"),
    ("fala", "saudacao"),
    ("fala aí", "saudacao"),
    ("fala fi", "saudacao"),
    ("salve", "saudacao"),
    ("salve ia", "saudacao"),
    ("beleza", "saudacao"),
    ("beleza ia", "saudacao"),
    ("tranquilo", "saudacao"),
    ("tudo tranquilo", "saudacao"),
    ("tudo certo por aí", "saudacao"),
    ("como está", "saudacao"),
    ("como está ia", "saudacao"),
    ("tem alguém aí", "saudacao"),
    ("tem alguem ai", "saudacao"),
    ("você está aí", "saudacao"),
    ("você está online", "saudacao"),
    ("iniciar conversa", "saudacao"),
    ("inicie conversa", "saudacao"),
    ("começar conversa", "saudacao"),
    ("oi assistente", "saudacao"),
    ("olá assistente", "saudacao"),
    ("oi inteligência artificial", "saudacao"),
    ("olá inteligência artificial", "saudacao"),
    ("oi computador", "saudacao"),
    ("olá computador", "saudacao"),
    ("bom dia ia", "saudacao"),
    ("boa tarde ia", "saudacao"),
    ("boa noite ia", "saudacao"),
    ("bom dia assistente", "saudacao"),
    ("boa tarde assistente", "saudacao"),
    ("boa noite assistente", "saudacao"),
    ("fala comigo", "saudacao"),
    ("vamos conversar", "saudacao"),
    ("oi tudo certo", "saudacao"),
    ("olá tudo bem", "saudacao"),
    ("oi tudo tranquilo", "saudacao"),
    ("eai tudo bem", "saudacao"),
    ("e aí tudo certo", "saudacao"),
    ("opa", "saudacao"),
    ("opa ia", "saudacao"),
    ("opa tudo bem", "saudacao"),
    ("cheguei", "saudacao"),
    ("estou aqui", "saudacao"),
    ("iniciar ia", "saudacao"),
    ("acordou ia", "saudacao"),
    ("pronto ia", "saudacao"),
    ("oi chat", "saudacao"),
    ("olá chat", "saudacao"),
    ("oi robô", "saudacao"),
    ("olá robô", "saudacao"),


    #Encerramento

    ("sair", "encerrar"),
    ("encerrar", "encerrar"),
    ("fechar sistema", "encerrar"),
    ("desligar", "encerrar"),
    ("desligar sistema", "encerrar"),
    ("feche o sistema", "encerrar"),
    ("fechar a ia", "encerrar"),
    ("feche a ia", "encerrar"),
    ("desligar a ia", "encerrar"),
    ("desligue a ia", "encerrar"),
    ("encerre a ia", "encerrar"),
    ("encerrar a ia", "encerrar"),
    ("finalizar ia", "encerrar"),
    ("finalize a ia", "encerrar"),
    ("parar ia", "encerrar"),
    ("pare a ia", "encerrar"),
    ("desative a ia", "encerrar"),
    ("desativar a ia", "encerrar"),
    ("apagar a ia", "encerrar"),
    ("apague a ia", "encerrar"),
    ("fechar assistente", "encerrar"),
    ("feche o assistente", "encerrar"),
    ("desligar assistente", "encerrar"),
    ("desligue o assistente", "encerrar"),
    ("encerrar assistente", "encerrar"),
    ("encerre o assistente", "encerrar"),
    ("finalizar assistente", "encerrar"),
    ("finalize o assistente", "encerrar"),
    ("sair do sistema", "encerrar"),
    ("quero sair", "encerrar"),
    ("pode sair", "encerrar"),
    ("pode encerrar", "encerrar"),
    ("pode desligar", "encerrar"),
    ("termine o sistema", "encerrar"),
    ("terminar sistema", "encerrar"),
    ("desligue o sistema", "encerrar"),
    ("encerre o sistema", "encerrar"),
    ("finalize o sistema", "encerrar"),
    ("pare o sistema", "encerrar"),
    ("interrompa o sistema", "encerrar"),
    ("desligue tudo", "encerrar"),
    ("encerrar programa", "encerrar"),
    ("fechar programa", "encerrar"),
    ("sair do programa", "encerrar"),
    ("desligar programa", "encerrar"),
    ("até mais ia", "encerrar"),
    ("obrigado pode fechar", "encerrar"),
    ("obrigado pode desligar", "encerrar"),


    # Hino Nacional
    
    ("toca o hino", "tocar_hino"),
    ("tocar hino", "tocar_hino"),
    ("toca o hino nacional", "tocar_hino"),
    ("tocar o hino nacional", "tocar_hino"),
    ("toque o hino nacional", "tocar_hino"),
    ("hino nacional", "tocar_hino"),
    ("hino nacional brasileiro", "tocar_hino"),
    ("hino do brasil", "tocar_hino"),
    ("hino brasileiro", "tocar_hino"),
    ("iniciar hino", "tocar_hino"),
    ("iniciar o hino", "tocar_hino"),
    ("inicie o hino", "tocar_hino"),
    ("começa o hino", "tocar_hino"),
    ("começar o hino", "tocar_hino"),
    ("comece o hino", "tocar_hino"),
    ("dar início ao hino", "tocar_hino"),
    ("inicie o hino nacional", "tocar_hino"),
    ("comece o hino nacional", "tocar_hino"),
    ("quero ouvir o hino", "tocar_hino"),
    ("quero ouvir o hino nacional", "tocar_hino"),
    ("quero escutar o hino", "tocar_hino"),
    ("quero escutar o hino nacional", "tocar_hino"),
    ("reproduzir hino", "tocar_hino"),
    ("reproduzir o hino", "tocar_hino"),
    ("reproduza o hino", "tocar_hino"),
    ("reproduzir hino nacional", "tocar_hino"),
    ("reproduza o hino nacional", "tocar_hino"),
    ("coloque o hino", "tocar_hino"),
    ("coloque o hino nacional", "tocar_hino"),
    ("colocar o hino", "tocar_hino"),
    ("colocar o hino nacional", "tocar_hino"),
    ("execute o hino", "tocar_hino"),
    ("executar o hino", "tocar_hino"),
    ("execute o hino nacional", "tocar_hino"),
    ("executar o hino nacional", "tocar_hino"),
    ("inicie a reprodução do hino", "tocar_hino"),
    ("reproduza o hino brasileiro", "tocar_hino"),
    ("toque o hino brasileiro", "tocar_hino"),
    ("vamos ouvir o hino", "tocar_hino"),
    ("vamos ouvir o hino nacional", "tocar_hino"),
    ("hora do hino", "tocar_hino"),
    ("é hora do hino", "tocar_hino"),
    ("inicie a cerimônia com o hino", "tocar_hino"),
    ("toque o hino da bandeira", "tocar_hino"),
    ("ligue o hino nacional", "tocar_hino"),
    ("coloque a música do hino nacional", "tocar_hino"),
    ("inicie o hino do brasil", "tocar_hino"),
    ("toque o hino do brasil", "tocar_hino"),
    ("quero o hino nacional brasileiro", "tocar_hino"),
    ("por favor toque o hino", "tocar_hino"),
    ("por favor toque o hino nacional", "tocar_hino"),
    ("pode tocar o hino", "tocar_hino"),
    ("pode tocar o hino nacional", "tocar_hino"),
    ("gostaria de ouvir o hino nacional", "tocar_hino"),
    ("ative o hino nacional", "tocar_hino"),
    ("inicie a execução do hino", "tocar_hino"),
    ("coloque para tocar o hino", "tocar_hino"),
    ("tocar o hino do brasil", "tocar_hino"),
    ("iniciar o hino do brasil", "tocar_hino"),
    ("execute o hino do brasil", "tocar_hino"),
    ("abra o hino nacional", "tocar_hino"),
    ("abra o hino do brasil", "tocar_hino"),
    ("quero escutar o hino brasileiro", "tocar_hino"),
    ("inicie a música do hino nacional", "tocar_hino"),

    # Aulas do dia
    
    ("aulas de hoje", "aulas_do_dia"),
    ("quais são as aulas de hoje", "aulas_do_dia"),
    ("o que tem hoje", "aulas_do_dia"),
    ("matérias de hoje", "aulas_do_dia"),
    ("horário de hoje", "aulas_do_dia"),
    ("que aulas tem hoje", "aulas_do_dia"),
    ("ver aulas do dia", "aulas_do_dia"),
    ("aulas do dia", "aulas_do_dia"),
    ("horário das aulas", "aulas_do_dia"),
    ("qual o horário hoje", "aulas_do_dia"),


]

frases = [item[0] for item in Dados]
intencoes = [item[1] for item in Dados]
modelo = Pipeline([
    ("tfidf", TfidfVectorizer( ngram_range=(1, 3), analyzer = "char_wb")),
    ("classificador", SVC(kernel="linear",probability=True,C=10))
])
print("Treinando a IA Escolar...")
modelo.fit(frases,intencoes)

testes = [
    "acende a luz por favor",
    "quero fazer a chamada agora",
    "me dá informações sobre o aluno João",
    "desliga tudo na quadra",
    "oi tudo bem",
]

print("\nTestando o modelo:")
print("-"*40)
for frases in testes:
    intencao = modelo.predict([frases])[0]
    print(f"'{frases}' -> '{intencao}'")

pasta_atual = os.path.dirname(os.path.abspath(__file__))
caminho_modelo = os.path.join(pasta_atual, "modelo.pkl")
with open(caminho_modelo, "wb") as arquivo:
    pickle.dump(modelo, arquivo)
print("-"*40)

print(f"Modelo salvo em: '{caminho_modelo}'")
    